config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

from core.users.views import UserCreateView

from django_email_verification import urls as email_urls  # include the urls


urlpatterns = [
    path(
        '',
        include('core.store.urls'),
    ),
    path(
        'articles/',
        include('core.articles.urls'),
    ),
    path(
        '',
        include('core.cart.urls'),
    ),
    path('',include('core.users.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True)),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('email/', include(email_urls)),  # connect them to an arbitrary path
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

core/articles/urls.py
from django.urls import path
from core.articles.views import ArticleCreateView, ArticleFormView

app_name = 'article'
urlpatterns = [
    # Home page
    path('new', ArticleCreateView.as_view(), name='create'),
    # Detail artilce
    path('<slug:slug>', ArticleFormView.as_view(),
         name='show'),
]

core/cart/urls.py
from django.urls import path
from core.cart.views import (
    CancelView,
    CartView,
    DecreaseQuantityOrderItemView,
    IncreaseQuantityOrderItemView,
    RemoveOrderItemView,
    Checkout,
    CreateCheckoutSessionView,
    SuccessView,
    stripe_webhook,
)

app_name = 'cart'
urlpatterns = [
    path('cart/', CartView.as_view(), name='summary'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
    path(
        'cart/item/increase/<uuid:id>',
        IncreaseQuantityOrderItemView.as_view(),
        name='item-increase',
    ),
    path(
        'cart/item/decrease/<uuid:id>',
        DecreaseQuantityOrderItemView.as_view(),
        name='item-decrease',
    ),
    path(
        'cart/item/remove/<uuid:id>', RemoveOrderItemView.as_view(), name='item-remove'
    ),
    # That we dont use anymore idk why
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('order/success/', SuccessView.as_view(), name='process-succeed'),
    path('order/cancel/', CancelView.as_view(), name='process-canceled'),
    # TODO Figure out how works that
    path(
        'create-checkout-session/',
        CreateCheckoutSessionView.as_view(),
        name='create-checkout-session',
    ),
]

core/store/urls.py
from django.urls import path
from core.store.views import ArticleListView

app_name = 'store'
urlpatterns = [
    # Home page
    path('', ArticleListView.as_view(), name='index')
]

core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/cart/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

from core.cart.validators import validate_positive

from core.articles.models import Article
from core.users.models import CustomUser

import uuid


class DiscountCode(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    code = models.CharField(unique=True, max_length=6)
    discount = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)


class Order(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    customer = models.ForeignKey(
        CustomUser, null=True, on_delete=models.SET_NULL)
    ordered = models.BooleanField(default=False)
    total = models.FloatField(default=0, validators=[validate_positive])
    discount_code = models.ForeignKey(
        DiscountCode,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    def completed(self):
        self.ordered = True
        self.save()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class OrderItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    article = models.ForeignKey(
        Article, on_delete=models.SET_NULL,
        null=True,
        related_name='orderitems'
    )
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, null=True, related_name='orderitems'
    )
    # cover_image = ForeignKey()
    quantity = models.IntegerField(default=1, null=True, blank=True)

    def item_sold(self):
        self.article.stock -= self.quantity
        self.article.save()

core/cart/views.py
import stripe
from core.articles.models import Article
from core.cart.models import Order, OrderItem
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import get_template
from django.urls import reverse
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessView(TemplateView):
    template_name = 'cart/success.html'


class CancelView(TemplateView):
    template_name = 'cart/cancel.html'


class CreateCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        order = Order.objects.get(
            customer_id=self.request.user.id, ordered=False)
        order_items = order.orderitems.all().order_by('-id')
        articles = Article.objects.all()
        line_items = []

        for item in order_items:
            article = articles.filter(id=item.article_id).first()
            price_object = {
                'price_data': {
                    'currency': 'usd',
                    'unit_amount': article.price,
                    'product_data': {
                        'name': article.title[:60],
                    },
                },
                'quantity': item.quantity,
            }
            line_items.append(price_object)

        try:
            checkout_session = stripe.checkout.Session.create(
                customer_email=self.request.user.email,
                billing_address_collection='auto',
                shipping_rates=['shr_1JJ21wH70q2DLVwFniELrAcf'],
                shipping_address_collection={
                    'allowed_countries': ['US', 'CA', 'MX'],
                },
                payment_method_types=[
                    'card',
                ],
                line_items=line_items,
                metadata={
                    'order_id': order.id
                },
                mode='payment',
                success_url=self.request.build_absolute_uri(
                    reverse('cart:process-succeed')
                ),
                cancel_url=self.request.build_absolute_uri(
                    reverse('cart:process-canceled')
                ),
            )

        except Exception as e:
            print(e)
            return str(e)

        return redirect(checkout_session.url)


class Checkout(TemplateView):
    template_name = 'cart/checkout.html'

    def get_context_data(self, **kwargs):
        context = super(Checkout, self).get_context_data(**kwargs)
        return context


class CartView(TemplateView):
    template_name = 'cart/summary.html'

    # TODO conseguir solo los datos que quiere
    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        order_items = (
            OrderItem.objects.select_related('article')  # type:ignore
            .prefetch_related('article__imagearticles')
            .filter(order__customer=self.request.user, order__ordered=False)
        )
        length_order_items = len(order_items)
        context['length_order_items'] = length_order_items
        context['order_items'] = []
        context['order_total'] = 0

        if length_order_items == 0:
            context['empty'] = True
            return context

        i = 0
        for order_item in order_items:

            i += 1

            article_image = order_item.article.imagearticles.get(order=1).image
            data = {
                'id': order_item.id,
                'image': article_image,
                'title': order_item.article.title,
                'price': order_item.article.get_display_price,
                'quantity': order_item.quantity,
                'stock': order_item.article.stock,
                'total': order_item.article.price * order_item.quantity,
                'slug': order_item.article.slug,
            }
            if i == length_order_items:
                data['last_item'] = True

            context['order_total'] += data['price'] * data['quantity']
            context['order_items'].append(data)

        return context


class IncreaseQuantityOrderItemView(View):
    def get(self, request, *args, **kwargs):
        order_item = OrderItem.objects.select_related('article').get(
            id=kwargs['id'])
        article = order_item.article

        if article.stock >= order_item.quantity + 1:
            order_item.quantity += 1
            order_item.save()
        else:
            messages.warning(self.request, 'There is not enough stock')

        return redirect('cart:summary')


class DecreaseQuantityOrderItemView(View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['id'])
        if order_item.quantity == 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect('cart:summary')


class RemoveOrderItemView(View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['id'])
        order_item.delete()
        return redirect('cart:summary')


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        customer_name = session['shipping']['name']
        customer_email = session['customer_email']
        customer_shipping = session['shipping']
        amount_total = session['amount_total'] / 100

        order_id = session['metadata']['order_id']
        order = Order.objects.prefetch_related('orderitems').get(id=order_id)
        # order.completed()
        order_items = order.orderitems.all()

        order_items_data = []
        products_bought = {}

        for item in order_items:

            # item.item_sold()

            article_data = {
                'title': item.article.title[:90] + '...',
                'price': item.article.price / 100,
                'quantity': item.quantity,
                'total': (item.article.price / 100) * item.quantity,
            }

            order_items_data.append(article_data)

            seller_email = item.article.author.email 

            if seller_email in products_bought:
                products_bought[seller_email].append(article_data)
            else:
                products_bought[seller_email] = [article_data]

        # print(products_bought)

        order_data = {
            'amount_total': amount_total,
            'updated_at': order.updated_at,
            'order_items': order_items_data,
            'name': customer_name,
        }


        # send a mail to customer
# 
#         template = get_template('cart/success_purchase.html')
#         html_content = template.render(order_data)
#         subject, from_email, to = f'Success purchase! Your order id is {order_id}', settings.EMAIL_HOST_USER, [customer_email]
# 
#         email = EmailMessage(subject, html_content, from_email, to)
#         email.content_subtype = 'html'
#         email.send()
# 
# 
# 

        # send a mail to seller

        for email in products_bought:
            order_data = {
                'amount_total': amount_total,
                'updated_at': order.updated_at,
                'products_bought': list(products_bought[email]),
                'customer_name': customer_name,
                'customer_shipping': customer_shipping
            }

            print(order_data['customer_shipping'])

            template = get_template('cart/product_bought.html')
            html_content = template.render(order_data)
            subject, from_email, to = 'Product bought! You had better send your product', settings.EMAIL_HOST_USER, [email]

            email = EmailMessage(subject,html_content,from_email,to)
            email.content_subtype= 'html'
            email.send()
 

    # Passed signature verification
    return HttpResponse(status=200)

templates/cart/cancel.html
{% extends 'base.html' %}
{% block content %}
<div class="card w-50 mx-auto">
  <div class="card-body">
    <h5 class="h1 card-title">Process Canceled</h5>
    <p class="card-text">Forgot to add something to your cart? Shop around then come back to pay!</p>
    <a href="{% url 'cart:summary' %}" class="btn btn-primary">Go to cart!</a>
  </div>
</div>
{% endblock content %}

templates/cart/cart.html
{% extends 'base.html' %}
{% block title %}Ecommerce - Cart{% endblock %}
{% load static %}
{% block content %}
{% if empty == False %}
<!--Section: Block Content-->
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down"
  id="chevron-down" viewBox="0 0 16 16" style="display: none;">
  <path fill-rule="evenodd"
    d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
</svg>
<section>

  <!--Grid row-->
  <div class="row">

    <!--Grid column-->
    <div class="col-lg-8">

      <!-- Card -->
      <div class="card wish-list mb-3">
        <div class="card-body">

          <h5 class="mb-4">Cart (<span>2</span> items)</h5>

          {% for order_item in order_items %}
          <div class="row mb-4">
            <div class="col-md-5 col-lg-3 col-xl-3">
              <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                <a href="{% url 'article:show' slug=order_item.slug %}">
                  <div class="mask waves-effect waves-light">
                    <img class="img-fluid w-100" src="{{ order_item.image.url }}">
                    <div class="mask rgba-black-slight waves-effect waves-light"></div>
                  </div>
                </a>
              </div>
            </div>
            <div class="col-md-7 col-lg-9 col-xl-9">
              <div>
                <div class="d-flex justify-content-between text-center">
                  <div>
                    <h5>{{ order_item.title | truncatechars:36 }}</h5>
                  </div>
                  <div>
                    <div class="text-center" style="border: 1px solid #ced4da;">
                      <a href="{% url 'cart:item-decrease' id=order_item.id %}" class="text-decoration-none px-2">-</a>
                      <p class="d-inline-block mb-0 py-1 px-3"
                        style="border-left: 1px solid #ced4da; border-right: 1px solid #ced4da;">{{order_item.quantity}}
                      </p>
                      <a href="{% url 'cart:item-increase' id=order_item.id %}" class="text-decoration-none px-2">+</a>
                    </div>
                    <small class="form-text text-muted">
                      Stock: {{ order_item.stock}}
                    </small>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center pt-3">
                  <div>
                    <a href="{% url 'cart:item-increase' id=order_item.id %}" type="button"
                      class="card-link-secondary small text-uppercase mr-3"><i class="fas fa-trash-alt mr-1"></i> Remove
                      item </a>
                  </div>
                  <p class="mb-0"><span><strong>${{ order_item.price }}</strong></span></p>
                </div>
              </div>
            </div>
          </div>
          <hr class="mb-4">
          {% endfor %}
        </div>
      </div>
      <!-- Card -->

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-4">

      <!-- Card -->
      <div class="card mb-3">
        <div class="card-body">

          <h5 class="mb-3">The total amount of</h5>

          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
              Temporary amount
              <span>${{ order_total_without_iva }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
              Shipping
              <span>Gratis</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
              <div>
                <strong>The total amount of</strong>
                <strong>
                  <p class="mb-0">(including VAT)</p>
                </strong>
              </div>
              <span><strong>$ {{ order_total_with_iva }}</strong></span>
            </li>
          </ul>

          <div class="d-grid mb-2">
            <a href="{% url 'checkout' %}" class="btn btn-success btn-block waves-effect waves-light">Go to checkout</a>
          </div>

        </div>
      </div>
      <!-- Card -->

      <!-- Card -->
      <!--       <div class="card mb-3"> -->
      <!--         <div class="card-body"> -->
      <!--  -->
      <!--           <a class="dark-grey-text d-flex justify-content-between" id="discountBtn" data-bs-toggle="collapse" href="#collapseExample" role="button" -->
      <!--             aria-expanded="false" aria-controls="collapseExample"> -->
      <!--             Add a discount code (optional) -->
      <!--             <span> -->
      <!--             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" ><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/> -->
      <!--             </svg> -->
      <!--             </span> -->
      <!--           </a> -->
      <!--  -->
      <!--           <div class="collapse" id="collapseExample"> -->
      <!--             <div class="mt-3"> -->
      <!--               <form action="" method="get">  -->
      <!--                 <div class="md-form md-outline mb-0 input-group"> -->
      <!--                   <input type="text" id="discount-code" class="form-control font-weight-light" -->
      <!--                     placeholder="Enter discount code"> -->
      <!--                     <div class="input-group-append"> -->
      <!--                       <button class="btn btn-primary" type="button">Apply</button> -->
      <!--                     </div> -->
      <!--                 </div> -->
      <!--               </form> -->
      <!--  -->
      <!--             </div> -->
      <!--           </div> -->
      <!--         </div> -->
      <!--       </div> -->
      <!-- Card -->

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->

</section>
<!--Section: Block Content-->
{% else %}
<div class="card w-50 mx-auto">
  <div class="card-body">
    <h5 class="h1 card-title">Your cart is empty</h5>
    <p class="card-text">Not sure what to buy? Thousands of products await you!</p>
    <a href="{% url 'store:index' %}" class="btn btn-primary">Go to buy!</a>
  </div>
</div>
{% endif %}
<script src="{% static 'js/cart.js' %}" charset="utf-8"></script>
{% endblock content %}

templates/cart/success.html
{% extends 'base.html' %}
{% block content %}
<div class="card w-50 mx-auto">
  <div class="card-body">
    <h5 class="h1 card-title">Payment Success!</h5>
    <p class="card-text">Thanks for your purchase. Check your email to track your package and see the details of your purchase</p>
    <a href="{% url 'store:index' %}" class="btn btn-primary">Go to home!</a>
  </div>
</div>

{% endblock content%}

templates/cart/success_purchase.html
<!DOCTYPE html>
<html lang="en">

<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>

<body>
	<h2>Thanks {{ name }} for your purchase! {{updated_at}}</h2>

	<p>In the next days, you will receive a email with instructions</p>
	<p>You spent ${{ amount_total }} dls. You bought the following:</p>
	<br>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Product</th>
				<th scope="col">Price</th>
				<th scope="col">Quantity</th>
				<th scope="col">Total</th>
			</tr>
		</thead>
		<tbody>
			{% for item in order_items %}
			<tr>
				<td>{{ item.title }}</td>
				<td>${{ item.price }} dls</td>
				<td>{{ item.quantity }}</td>
				<td>${{ item.total }} dls</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</body>

</html>

templates/cart/summary.html
{% extends 'base.html' %}
{% block title %}Ecommerce - Cart{% endblock %}
{% block content %}
{% if empty == null %}
<!--Section: Block Content-->
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down"
  id="chevron-down" viewBox="0 0 16 16" style="display: none;">
  <path fill-rule="evenodd"
    d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
</svg>
<section>

  <!--Grid row-->
  <div class="row">

    <!--Grid column-->
    <div class="col-lg-8">

      <!-- Card -->
      <div class="card wish-list mb-3">
        <div class="card-body">

          <h5 class="mb-4">Cart (<span>{{ length_order_items }}</span> items)</h5>

          {% for order_item in order_items %}
          <div class="row mb-4">
            <div class="col-md-5 col-lg-3 col-xl-3">
              <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                <a href="{% url 'article:show' slug=order_item.slug %}">
                  <div class="mask waves-effect waves-light">
                    <img class="img-fluid w-100" src="{{ order_item.image.url }}">
                    <div class="mask rgba-black-slight waves-effect waves-light"></div>
                  </div>
                </a>
              </div>
            </div>
            <div class="col-md-7 col-lg-9 col-xl-9">
              <div>
                <div class="d-flex justify-content-between text-center">
                  <div>
                    <h5>{{ order_item.title | truncatechars:36 }}</h5>
                  </div>
                  <div>
                    <div class="text-center" style="border: 1px solid #ced4da;">
                      <a href="{% url 'cart:item-decrease' id=order_item.id %}" class="text-decoration-none px-2">-</a>
                      <p class="d-inline-block mb-0 py-1 px-3"
                        style="border-left: 1px solid #ced4da; border-right: 1px solid #ced4da;">{{order_item.quantity}}
                      </p>
                      <a href="{% url 'cart:item-increase' id=order_item.id %}" class="text-decoration-none px-2">+</a>
                    </div>
                    <small class="form-text text-muted">
                      Stock: {{ order_item.stock}}
                    </small>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center pt-3">
                  <div>
                    <a href="{% url 'cart:item-remove' id=order_item.id %}" type="button"
                      class="card-link-secondary small text-uppercase mr-3"><i class="fas fa-trash-alt mr-1"></i> Remove
                      item </a>
                  </div>
                  <p class="mb-0"><span><strong>${{ order_item.price }}</strong></span></p>
                </div>
              </div>
            </div>
          </div>
            {% if order_item.last_item != True %}
            <hr class="mb-4">
            {% endif %}
          {% endfor %}
        </div>
      </div>
      <!-- Card -->

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-4">

      <!-- Card -->
      <div class="card mb-3">
        <div class="card-body">

          <h5 class="mb-3">The total amount of</h5>

          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
              Total amount
              <span>${{ order_total }}</span>
            </li>
          </ul>
          <hr class="mb-4">

          <form action="{% url 'cart:create-checkout-session' %}" method="POST" class="d-gid mb-2">
            <div class="d-grid mb-2">
                {% csrf_token %}
                <button type="" class="btn btn-success btn-block waves-effect waves-light">Go to checkout</button>
            </div>
          </form>

        </div>
      </div>
      <!-- Card -->

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->

</section>
<!--Section: Block Content-->
{% else %}
<div class="card w-50 mx-auto">
  <div class="card-body">
    <h5 class="h1 card-title">Your cart is empty</h5>
    <p class="card-text">Not sure what to buy? Thousands of products await you!</p>
    <a href="{% url 'store:index' %}" class="btn btn-primary">Go to buy!</a>
  </div>
</div>
{% endif %}
{% endblock content %}