config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

from core.users.views import UserCreateView

from django_email_verification import urls as email_urls  # include the urls


urlpatterns = [
    path(
        '',
        include('core.store.urls'),
    ),
    path(
        'articles/',
        include('core.articles.urls'),
    ),
    path(
        '',
        include('core.cart.urls'),
    ),
    path('',include('core.users.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True)),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('email/', include(email_urls)),  # connect them to an arbitrary path
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

core/articles/urls.py
from django.urls import path
from core.articles.views import ArticleCreateView, ArticleFormView

app_name = 'article'
urlpatterns = [
    # Home page
    path('new', ArticleCreateView.as_view(), name='create'),
    # Detail artilce
    path('<slug:slug>', ArticleFormView.as_view(),
         name='show'),
]

core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/articles/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify

from core.users.models import CustomUser

import uuid


class Article(models.Model):
    class ArticleObjects(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    class Meta:
        ordering = ('-created_at',)

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.TextField()
    price = models.PositiveBigIntegerField(
        default=0
    )  # here will store in cents NOT dollars
    stock = models.PositiveIntegerField()
    slug = models.SlugField(blank=True, unique=True, max_length=256)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    articleobjects = ArticleObjects()

    def __str__(self):
        return self.title

    @property
    def get_display_price(self):
        return self.price / 100  # type: ignore


def set_slug(sender, instance, *args, **kwargs):
    if instance.slug:
        return
    instance.slug = slugify('{}-{}'.format(instance.title, instance.id))


pre_save.connect(set_slug, sender=Article)


class ImageArticle(models.Model):
    class ImageArticleObjects(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(article_status='published', order=1)

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='imagearticles'
    )
    image = models.ImageField(
        upload_to='images/article/',
    )
    order = models.PositiveIntegerField()
    article_status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    imagearticleobjects = ImageArticleObjects()

    def __str__(self):
        return f'{self.article.title}-{self.id}'

    class Meta:
        ordering = ('-created_at',)

core/articles/forms.py
from django import forms


from core.articles.models import Article
from core.cart.models import OrderItem


class AddToCartForm(forms.ModelForm):

    class Meta:
        model = OrderItem
        fields = ('quantity',)

        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control'})}


class CreateArticleForm(forms.ModelForm):
    images = forms.FileField(
        required=True, widget=forms.FileInput(attrs={
            'class': 'form-control',
            'multiple': True,
        }))

    class Meta:
        model = Article
        fields = ('title', 'description', 'price', 'stock', 'status')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your title'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Type the description', 'rows': 5, 'style': 'resize: none'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Type the price'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Type the amount'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
        }

core/articles/views.py
# TODO check if the article's stock > 0 display
from django.db.models import Prefetch
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from core.articles.models import Article, ImageArticle
from core.cart.models import Order, OrderItem

from core.articles.forms import CreateArticleForm, AddToCartForm


class ArticleFormView(FormView):
    template_name = 'articles/article_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Article, slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse_lazy('cart:summary')

    def form_valid(self, form):
        # TODO improve method

        customer_id = self.request.user.id
        article_id = self.kwargs['slug'][-36:]
        quantity = int(form.cleaned_data['quantity'])
        order, order_created = Order.objects.get_or_create(
            customer_id=customer_id, ordered=False)

        order_item, order_item_created = OrderItem.objects.select_related(
            'article'
        ).get_or_create(
            article_id=article_id, order_id=order.id,
        )

        article_stock = order_item.article.stock
        enough_stock_of_article = article_stock >= order_item.quantity + quantity

        if order_item_created and enough_stock_of_article:
            order_item.quantity = quantity
            order_item.save()
            messages.success(self.request, 'The item was created in the cart')
        elif not order_item_created and enough_stock_of_article:
            order_item.quantity += quantity
            order_item.save()
            messages.success(self.request, 'The item was created in the cart')
        else:
            order_item.delete()
            messages.warning(self.request, 'There is not enough stock')

        return super(ArticleFormView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ArticleFormView, self).get_context_data(**kwargs)
        article = Article.objects.prefetch_related(
            Prefetch(
                'imagearticles',
                queryset=ImageArticle.objects.filter(
                    article__slug=self.kwargs['slug']
                ).order_by('order'),
                to_attr='get_images',
            )
        ).get(slug=self.kwargs['slug'])
        context['article'] = article
        context['article'].images = article.get_images

        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = CreateArticleForm
    # TODO When the article was created, redirect to the new article
    success_url = reverse_lazy('article:create')

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()
        images = self.request.FILES.getlist('images')

        order = 0

        for image in images:
            order += 1
            ImageArticle.objects.create(
                article=article, image=image, article_status=article.status, order=order
            )

        return super(ArticleCreateView, self).form_valid(form)

templates/articles/article_detail.html
{% extends 'base.html' %}
{% block title %}Ecommerce - New Article{% endblock %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/article_detail.css' %}" type="text/css" media="screen" title="no title"
	charset="utf-8">
{% endblock head %}

{% block content %}
<div class="row">
	<div class="product col-12 col-lg-5 mb-4">
		<div class="main-img">
			<img src="{{ article.images.0.image.url }}" class="pro-img" alt="{{ article.images.0.title }}">
		</div>
		<div class="thumb-img mt-4">
			{% for image_article in article.images %}
			<div class="box" onclick="changeImage(this)">
				<img src="{{ image_article.image.url }}" alt="{{ article.images.0.title }}">
			</div>
			{% endfor %}
		</div>
	</div>
	<div class="col-11 col-lg-7">
		<h1>{{ article.title }}</h1>
		<div>
			<p>{{ article.description }}</p>
			<p>Stock: {{ article.stock }}</p>
			<p style="display: inline-block;">Price: ${{ article.get_display_price }} dls</p>
		</div>
		<div>
			<form method="POST">
				{% csrf_token %}
				{{ form.quantity.label }}
				{{ form.quantity }}
				<button type="submit" class="btn btn-success mt-4">Add to cart</button>
			</form>
		</div>
	</div>

</div>
<script src="{% static 'js/article_detail.js' %}" charset="utf-8"></script>
{% endblock content %}

templates/articles/article_form.html
{% extends 'base.html' %}
{% block title %}Ecommerce - New Article{% endblock %}
{% block content %}
<style>
	@media (max-width:992px) {
		.form-custom {
			width: 50%;
		}
	}
</style>

<h1 class="text-center my-4">Add a new article</h1>
<div class="p-4">
	<div class="mx-auto p-4 form-custom" style="width: 90%; background: #f0f0f0;">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-label py-1">
				<label for="id_title" class="form-label">Title</label>
				{{ form.title}}
			</div>
			<div class="form-label py-1">
				<label for="id_description" class="form-label">Description</label>
				{{ form.description}}
			</div>
			<div class="form-label py-1">
				<label for="id_price" class="form-label">Price</label>
				{{ form.price }}
			</div>
			<div class="form-label py-1">
				<label for="id_stock" class="form-label">Stock</label>
				{{ form.stock }}
			</div>
			<div class="form-label py-1">
				<label for="id_status" class="form-label">Status</label>
				{{ form.status }}
			</div>
			<div class="form-label py-1">
				<label for="id_images" class="form-label">Images</label>
				{{ form.images }}
			</div>
			<div class="d-grid mt-5 mb-2">
				<button type="submit" class="btn btn-primary mb-3">Submit</button>
			</div>
		</form>
		{{ form.errors }}
	</div>
</div>

{% endblock %}

templates/articles/new.html
{% extends 'base.html' %}
{% block title %}Ecommerce - New Article{% endblock %}
{% block content %}
<style>
	@media (max-width:992px) {
		.form-custom {
			width: 50%;
		}
	}
</style>

<h1 class="text-center my-4">Add a new article</h1>
<div class="p-4">
	<div class="mx-auto p-4 form-custom" style="width: 90%; background: #f0f0f0;">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-label py-1">
				<label for="id_title" class="form-label">Title</label>
				{{ form.title}}
			</div>
			<div class="form-label py-1">
				<label for="id_description" class="form-label">Description</label>
				{{ form.description}}
			</div>
			<div class="form-label py-1">
				<label for="id_price" class="form-label">Price</label>
				{{ form.price }}
			</div>
			<div class="form-label py-1">
				<label for="id_stock" class="form-label">Stock</label>
				{{ form.stock }}
			</div>
			<div class="form-label py-1">
				<label for="id_status" class="form-label">Status</label>
				{{ form.status }}
			</div>
			<div class="form-label py-1">
				<label for="id_images" class="form-label">Images</label>
				{{ form.images }}
			</div>
			<div class="d-grid mt-5 mb-2">
				<button type="submit" class="btn btn-primary mb-3">Submit</button>
			</div>
		</form>
		{{ form.errors }}
	</div>
</div>

{% endblock %}