config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

from core.users.views import UserCreateView

from django_email_verification import urls as email_urls  # include the urls


urlpatterns = [
    path(
        '',
        include('core.store.urls'),
    ),
    path(
        'articles/',
        include('core.articles.urls'),
    ),
    path(
        '',
        include('core.cart.urls'),
    ),
    path('',include('core.users.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True)),
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('email/', include(email_urls)),  # connect them to an arbitrary path
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

core/articles/urls.py
from django.urls import path
from core.articles.views import ArticleCreateView, ArticleFormView

app_name = 'article'
urlpatterns = [
    # Home page
    path('new', ArticleCreateView.as_view(), name='create'),
    # Detail artilce
    path('<slug:slug>', ArticleFormView.as_view(),
         name='show'),
]

core/cart/urls.py
from django.urls import path
from core.cart.views import (
    CancelView,
    CartView,
    DecreaseQuantityOrderItemView,
    IncreaseQuantityOrderItemView,
    RemoveOrderItemView,
    Checkout,
    CreateCheckoutSessionView,
    SuccessView,
    stripe_webhook,
)

app_name = 'cart'
urlpatterns = [
    path('cart/', CartView.as_view(), name='summary'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
    path(
        'cart/item/increase/<uuid:id>',
        IncreaseQuantityOrderItemView.as_view(),
        name='item-increase',
    ),
    path(
        'cart/item/decrease/<uuid:id>',
        DecreaseQuantityOrderItemView.as_view(),
        name='item-decrease',
    ),
    path(
        'cart/item/remove/<uuid:id>', RemoveOrderItemView.as_view(), name='item-remove'
    ),
    # That we dont use anymore idk why
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('order/success/', SuccessView.as_view(), name='process-succeed'),
    path('order/cancel/', CancelView.as_view(), name='process-canceled'),
    # TODO Figure out how works that
    path(
        'create-checkout-session/',
        CreateCheckoutSessionView.as_view(),
        name='create-checkout-session',
    ),
]

core/store/urls.py
from django.urls import path
from core.store.views import ArticleListView

app_name = 'store'
urlpatterns = [
    # Home page
    path('', ArticleListView.as_view(), name='index')
]

core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{% block title %}{% endblock title %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.0.1/dist/lux/bootstrap.min.css"
		integrity="undefined" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static '/css/base.css' %}" type="text/css" media="screen" charset="utf-8">
	{% block head %}{% endblock head %}
</head>

<body>

	<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		<symbol id="ecommerce" viewBox="0 0 512.005 512.005">
			<title>Ecommerce</title>
			<path
				d="m507.505 116.364c-3.798-4.66-9.491-7.364-15.502-7.364h-362.257l-1.493-13.644c-.016-.142-.033-.284-.051-.426-7.101-54.118-53.616-94.93-108.199-94.93-11.046 0-20 8.954-20 20s8.954 20 20 20c34.508 0 63.926 25.751 68.513 59.934l28.754 262.769c2.646 24.178 15.816 44.82 34.659 57.577-26.139 38.445 2.253 91.998 49.074 91.72 39.778.551 69.171-40.626 55.861-78h86.277c-13.304 37.378 16.077 78.55 55.862 78 78.267-3.238 78.252-114.769-.001-118h-202.207c-20.444 0-37.539-15.326-39.763-35.649l-.585-5.351h244.65c37.783 0 70.737-26.86 78.356-63.867l10.521-51.1c1.212-5.889-.289-12.01-4.087-16.669-3.798-4.66-9.491-7.364-15.502-7.364h-89.958l5.2-65h81.839l-.405 1.967c-2.227 10.819 4.737 21.395 15.556 23.622 1.361.28 2.717.415 4.054.415 9.292-.001 17.621-6.513 19.568-15.971l5.353-26c1.212-5.888-.289-12.01-4.087-16.669zm-108.502 317.636c10.477 0 19 8.523 19 19-1.044 25.206-36.96 25.199-38 0 0-10.477 8.523-19 19-19zm-198 0c10.477 0 19 8.523 19 19-1.044 25.206-36.96 25.199-38 0 0-10.477 8.523-19 19-19zm-66.88-285h78.255l5.2 65h-76.342zm17.947 164-6.456-59h75.165l4.72 59zm180.308 0h-66.752l-4.72-59h76.192zm7.92-99h-82.592l-5.2-65h92.992zm105.55 40-5.573 27.066c-3.81 18.504-20.286 31.934-39.178 31.934h-28.591l4.72-59z" />
	</svg>


	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<!-- USER -->
			{% if user.is_authenticated %}
			<div class="dropdown text-end mobile-icon">
				<a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
					data-bs-toggle="dropdown" aria-expanded="false">
					{% if user.profile_picture %}
					<img src="{{ user.profile_picture.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
					{% else %}
					<img src="{% static 'images/profile-picture.png' %}" alt="mdo" width="32" height="32" class="rounded-circle">
					{% endif %}
				</a>
				<ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
					<li><a class="dropdown-item" href="{% url 'article:create' %}">New article...</a></li>
					<li><a class="dropdown-item" href="#">Settings</a></li>
					<li><a class="dropdown-item" href="#">Profile</a></li>
					<li>
						<hr class="dropdown-divider">
					</li>
					<li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
				</ul>
			</div>
			{% endif %}


			<a href="{% url 'store:index' %}" class="navbar-brand">
				<svg class="bi me-2" width="54" height="54" role="img" aria-label="Ecommerce">
					<use xlink:href="#ecommerce" /></svg>
			</a>


			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="active nav-link px-2 link-secondary" aria-current="page"
							href="{% url 'store:index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="active nav-link px-2 link-secondary" aria-current="page" href="{% url 'cart:summary' %}">Cart</a>
					</li>
				</ul>
				<form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
					<input type="search" class="form-control" placeholder="Search..." aria-label="Search">
				</form>
				{% if user.is_authenticated %}
				<!-- User -->
				<div class="dropdown text-end mobile-icon1">
					<a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
						data-bs-toggle="dropdown" aria-expanded="false">
						{% if user.profile_picture %}
						<img src="{{ user.profile_picture.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
						{% else %}
						<img src="{% static 'images/profile-picture.png' %}" alt="mdo" width="32" height="32"
							class="rounded-circle">
						{% endif %}
					</a>
					<ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
						<li><a class="dropdown-item" href="{% url 'article:create' %}">New article...</a></li>
						<li><a class="dropdown-item" href="#">Settings</a></li>
						<li><a class="dropdown-item" href="#">Profile</a></li>
						<li>
							<hr class="dropdown-divider">
						</li>
						<li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
					</ul>
				</div>
				{% else %}
				<a href="{% url 'login' %}" type="button" class="btn btn-primary">Login</a>
				<a href="{% url 'signup' %}" type="button" class="btn btn-secondary">Sign Up</a>
				{% endif %}
			</div>

		</div>
	</nav>

	{% if messages %}
	{% for msg in messages %}
	<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		<symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
			<path
				d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
		</symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
	</svg>

  <div class="alert alert-{{ msg.tags }} d-flex align-items-center px-5" role="alert">
		<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
      {% if msg.tags == 'success' %}
        <use xlink:href="#check-circle-fill" /></svg>
      {% else %}
        <use xlink:href="#exclamation-triangle-fill"/></svg>
      {% endif %}
		<div>
			{{ msg }}
		</div>
	</div>
	{% endfor %}

	{% endif %}

	<main class="container my-5">
		{% block content %}{% endblock content %}
	</main>


	<footer class="footer mt-auto py-3 bg-light">
		<div class="container">
			<span class="text-muted">www.ecommerce.com | Design by Fernado Guerrero</span>
		</div>
	</footer>



	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
	</script>
</body>

</html>